### ISSUE TITLE
GitHub Actions failing

### ISSUE THREAD

**Issue by SvenNekula** [SvenNekula/newproject#2]
Hey @maxheld83 

so I set up GitHub actions, but it fails at:  _Run Rscript -e "deploy_path <- rmarkdown::render_site(encoding = 'UTF-8')"_

The error-message is: 
Error in library("gganimate") : there is no package called 'gganimate'
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> library

Execution halted
##[error]Process completed with exit code 1.

That's odd considering everything works fine when I render my site locally. 
Do you have any idea how I could fix that? Google didn't help me unfortunately.

Thanks in advance!

**Comment by maxheld83** [comment]
You need to list all the packages that you're using in `DESCRIPTION`, otherwise the runtime on GitHub Actions won't have these packages installed.
Remember, GitHub Actions starts with a blank(ish) computer, so it doesn't have everything that's on your machine.

An easy way to edit the `DESCRIPTION` is to use [`usethis::use_package()](https://usethis.r-lib.org/reference/use_package.html).

**Comment by SvenNekula** [comment]
Thank you @maxheld83 for responding so quickly.
I didn't really understand how to use the usethis-package in my description, so I just listed all used packages in my description. However, there is a new problem now. The package "gifski" won't install, resulting in following error-message:

------------------ RUST COMPILER NOT FOUND --------------------

Cargo was not found on the PATH. Please install cargo / rustc:

 - yum install cargo         (Fedora/CentOS)
 - apt-get install cargo     (Debian/Ubuntu)
 - brew install rustc        (MacOS)

Alternatively install Rust from: <https://www.rust-lang.org>

---------------------------------------------------------------

Not sure where to go from here. As the Rust-Compiler has to be installed on the GitHub Actions' machine, right?
Is there any way to get this to work?

**Comment by maxheld83** [comment]
yes, this is the not-so-fun part of using CI: system dependencies.
What you're missing in this case is a program installed in the CI, that's *not* an R package, that is required by {gifski}, either at compile time or at run time (not sure).

There's now a cool action that you can run that should automatically install missing system dependencies.

I'm going to add a PR to that effect since this is a bit finicky.
