### ISSUE TITLE
Things to do?

### ISSUE THREAD

**Issue by SvenNekula** [SvenNekula/newproject#9]
Hi @maxheld83 

I don't really know what to do with this project besides tyding up / adding some more text / pictures / etc.. and I don't really feel like it's enough to be graded yet. I'm also not sure where to go from what I have already done 😅 
Any ideas which packages I could look into that are useful to know / I haven't covered at all yet? 
Then I would add some more content to my project. 

Thanks!

**Comment by maxheld83** [comment]
I wouldn't worry about it being grade-able -- if you clean it up a bit more (ie. suppress warning and message output, maybe make more of it reproducible etc.) you're good to go.

*But* you can also try something new, since you seem to have this stuff pretty much under wraps.

I can think of a couple of directions you might go into:

1. More **wrangling** (i.e. {dplyr} and {tidyr}) use. 
  You got lucky in that your data was already pretty [tidy](https://r4ds.had.co.nz/tidy-data.html), requiring minimal transformation.
  You might find another dataset which is much more messy, and try to tidy it up, using the tooling in {dplyr} and {tidyr}.
  This (tidying up data) is one of the areas where tidyverse (hence the name) R really excels compared to other languages.
  And in real life, most data is incredibly messy.
2. Do some **functional programming**. R is really great at running loops, because lots of operations are vectorised by default and functional programming is a very useful paradigm in this regard. You might, for example, try to calculate a rolling 5-day average of new infections (or something) per country, since the data is a little noisy on a date-to-date basis (that also shows in the plot, which is pretty jagged). This would require you to split up the data into all these 5-day increments (which are a lot), and calculate the mean over these. There are a couple of approaches on how to do this in R, including {[purrr](https://purrr.tidyverse.org)} and {[slider](https://davisvaughan.github.io/slider/)}. Functional programming can be quite powerful and is super expressive in R.
3. Do some **modeling**, such as fitting a logarithmic function to the data per country of some such thing. http://tidymodels.org is a good place to start. This also would get you into the statistics.
4. Build something **interactive**, i.e. a website where people can get some dynamic results depending on their inputs. For simpler operations (such as subsetting the country) this can be done either in all-client-side-javascript via https://rstudio.github.io/crosstalk/ and https://www.htmlwidgets.org. (You actually have parts of this already with your usage of {DT}). For more extensive (actually, arbitrarily complex) operations, you could build a full-on shiny web app http://shiny.rstudio.com. For example, in a shiny web app, users might choose *how* long they'd like the rolling average to be (2, 3, 4, n days) and have the results update automatically. This would introduce you to **reactive programming** which is a whole different ball-game, and probably the most different from everything else.

As always, for each of these, there's plenty of additional resources in http://datascience.phil.fau.de/fossos/stack.html

**Comment by SvenNekula** [comment]
Thank you so much! 
I'll definetly look into all of that. 😊
